#!/bin/sh
# zynq-dtgen: generate a Zynq/ZynqMP root DTS + PL devicetree overlay from
# a Vivado .xsa hardware export, via Xilinx's xsct + device-tree-xlnx.
#
# Falls back to copying an already-committed devicetree directory if xsct
# or the .xsa are unavailable, or generation otherwise fails, so the build
# never hard-fails for lack of Xilinx tools. Either way a SOURCE.txt marker
# is dropped in the output dir saying which path was actually used.
set -e

XSCT="$1"; XSA="$2"; DTREPO="$3"; NAME="$4"; FALLBACK="$5"; OUT="$6"

rm -rf "$OUT"
mkdir -p "$OUT/xilinx"

# Some boards list pcw.dtsi unconditionally in BR2_TARGET_UBOOT_CUSTOM_DTS_PATH
# because a real xsct-generated zynq-7000.dtsi may #include it, but nothing
# in the committed (fallback) dts does. Guarantee it always exists - empty is
# fine when unused - so that same defconfig line works whether this run
# generated from a real .xsa or fell back to the committed dts.
ensure_companion_files() {
	[ -f "$OUT/xilinx/pcw.dtsi" ] || : > "$OUT/xilinx/pcw.dtsi"
}
trap ensure_companion_files EXIT

use_fallback() {
	reason="$1"
	echo "zynq-dtgen: WARNING: $reason" >&2
	echo "zynq-dtgen: WARNING: falling back to committed devicetree in '$FALLBACK'" >&2
	if [ -z "$FALLBACK" ] || [ ! -d "$FALLBACK" ]; then
		echo "zynq-dtgen: ERROR: no usable fallback dir ('$FALLBACK') - output will be empty" >&2
		{
			echo "FALLBACK FAILED: $reason"
			echo "No fallback dir available (BR2_PACKAGE_HOST_ZYNQ_DTGEN_FALLBACK_DIR=$FALLBACK)."
		} > "$OUT/SOURCE.txt"
		return 0
	fi
	cp -a "$FALLBACK/." "$OUT/xilinx/"
	{
		echo "SOURCE: repo (committed dts) - NOT generated from .xsa"
		echo "REASON: $reason"
		echo "FALLBACK_DIR: $FALLBACK"
		date
	} > "$OUT/SOURCE.txt"
}

if [ -z "$XSA" ]; then
	use_fallback "no .xsa path configured"
	exit 0
fi

if [ ! -f "$XSA" ]; then
	use_fallback "xsa not found: $XSA"
	exit 0
fi

if ! command -v "$XSCT" >/dev/null 2>&1 && [ ! -x "$XSCT" ]; then
	use_fallback "xsct not found: $XSCT"
	exit 0
fi

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"; ensure_companion_files' EXIT

# Run xsct against a throwaway copy of the .xsa, cd'd into $WORK: opening a
# hardware design makes xsct dump ps7_init.*/system.bit next to whatever .xsa
# it opened, plus a .Xil/ scratch dir in the cwd - neither of which should
# land in the board directory or the invoker's (build system's) cwd. Copying
# the .xsa and cd'ing means all of that lands under $WORK instead, which the
# trap above removes no matter how this script exits.
WORK_XSA="$WORK/$(basename "$XSA")"
cp "$XSA" "$WORK_XSA"

cat > "$WORK/gen.tcl" <<'TCL'
set xsa    [lindex $argv 0]
set repo   [lindex $argv 1]
set outdir [lindex $argv 2]

hsi::open_hw_design $xsa
set proc0 [lindex [hsi::get_cells -hier -filter {IP_TYPE==PROCESSOR}] 0]
hsi::set_repo_path $repo
hsi::create_sw_design zynq_dtgen -os device_tree -proc $proc0
hsi::generate_target -dir $outdir
TCL

if ! ( cd "$WORK" && "$XSCT" "$WORK/gen.tcl" "$WORK_XSA" "$DTREPO" "$WORK/gen" >"$WORK/xsct.log" 2>&1 ); then
	cat "$WORK/xsct.log" >&2
	use_fallback "xsct generation failed (see build log above)"
	exit 0
fi

GEN="$WORK/gen"
if [ ! -f "$GEN/system-top.dts" ]; then
	cat "$WORK/xsct.log" >&2
	use_fallback "xsct did not produce system-top.dts"
	exit 0
fi

# --- root dts (PS side): system-top.dts minus the pl.dtsi include, since
#     the PL side becomes the overlay below instead ---
{
	echo "/*"
	echo " * Auto-generated by zynq-dtgen from:"
	echo " *   $XSA"
	echo " * Do not hand-edit - see ${NAME}-fixup.dtsi for board-specific tweaks."
	echo " */"
	echo
	sed -e '/#include "pl\.dtsi"/d' "$GEN/system-top.dts"
} > "$OUT/xilinx/$NAME.dts"

for f in zynq-7000.dtsi zynqmp.dtsi pcw.dtsi; do
	[ -f "$GEN/$f" ] && cp "$GEN/$f" "$OUT/xilinx/"
done
[ -d "$GEN/include" ] && cp -a "$GEN/include" "$OUT/xilinx/"

# Board-specific manual fixups (e.g. reset-gpios polarity) live outside the
# generated tree and get included last, so re-running generation never
# clobbers them.
if [ -f "$FALLBACK/$NAME-fixup.dtsi" ]; then
	printf '\n#include "%s-fixup.dtsi"\n' "$NAME" >> "$OUT/xilinx/$NAME.dts"
	cp "$FALLBACK/$NAME-fixup.dtsi" "$OUT/xilinx/"
fi

# --- PL overlay: pl.dtsi is already just new top-level nodes (amba_pl bus +
#     any fixed-clocks), so wrap it as a /plugin/ fragment targeting "/" ---
if [ -f "$GEN/pl.dtsi" ]; then
	{
		echo "/*"
		echo " * Auto-generated by zynq-dtgen from:"
		echo " *   $XSA"
		echo " * PL fabric IP, as a devicetree overlay."
		echo " */"
		echo
		echo "/dts-v1/;"
		echo "/plugin/;"
		echo
		echo "/ {"
		echo "	fragment@0 {"
		echo "		target-path = \"/\";"
		echo "		__overlay__ {"
		sed -e '1,/^\/ {$/d' -e '$d' "$GEN/pl.dtsi" | sed 's/^/\t\t\t/'
		echo "		};"
		echo "	};"
		echo "};"
	} > "$OUT/xilinx/$NAME-pl.dtso"
fi

{
	echo "SOURCE: generated from .xsa via xsct + device-tree-xlnx"
	echo "XSA: $XSA"
	echo "DEVICE_TREE_XLNX: $DTREPO"
	date
} > "$OUT/SOURCE.txt"

echo "zynq-dtgen: generated $OUT/xilinx/$NAME.dts + $NAME-pl.dtso from $XSA"
