name: Build Buildroot Zynq RK7020F

on:
  push:
    branches: ["main", "runner_builder"]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set environment paths
        run: |
          echo "WORKSPACE_ROOT=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "BUILDROOT_DIR=$GITHUB_WORKSPACE/buildroot" >> $GITHUB_ENV
          echo "BR2_EXTERNAL=$GITHUB_WORKSPACE/buildroot_external" >> $GITHUB_ENV

      - name: Sanity check
        run: |
          echo "=== WORKSPACE ==="
          ls -lah $WORKSPACE_ROOT
          echo "=== BUILDROOT ==="
          ls -lah $BUILDROOT_DIR
          echo "=== EXTERNAL ==="
          ls -lah $BR2_EXTERNAL

      - name: Configure Buildroot
        working-directory: ${{ env.BUILDROOT_DIR }}
        run: |
          make BR2_EXTERNAL=$BR2_EXTERNAL zynq_rk7020f_defconfig

      - name: Build
        working-directory: ${{ env.BUILDROOT_DIR }}
        run: |
          make -j$(nproc)

      - name: Show artifacts
        working-directory: ${{ env.BUILDROOT_DIR }}
        run: |
          ls -lah output/images || true

      - name: Upload images
        uses: actions/upload-artifact@v4
        with:
          name: zynq-rk7020f-images
          path: buildroot/output/images